dataset:
  name: reentrant_2_debug
  env: extern/QGym/configs/env/reentrant_2.yaml
  output_dir: dataset/qgym

collection:
  n_steps: 10000
  n_valid: 1000
  n_test: 1000
  shard_size: 5000
  seed: 42
  force_collect: false
  policy: mixed
  policy_weights:
    random: 0.25
    sed: 0.25
    qmd: 0.25
    softmax: 0.25
