# @package _global_
logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  project: certiqnet-z2
  entity: ${oc.env:WANDB_ENTITY,null}
  save_dir: ${hydra:runtime.output_dir}
  mode: offline
  log_model: true
  tags:
    - z2
    - ${model._target_}
    - ${env.mu_mode}
